### ISSUE TITLE
isContourConvex support 

### ISSUE THREAD

**Issue by Designify101** [rainyl/opencv_dart#297]

**Comment by rainyl** [comment]
@Designify101 Get it. Will add the function when having some time. :)

Or do you have time to work on it? @abdelaziz-mahdy 

References:
- https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html#ga8abf8010377b58cbc16db6734d92941b
- https://github.com/rainyl/dartcv/blob/1ba6e92ab11c563be9bee0607ceb182dcf18a6b6/dartcv/imgproc/imgproc.h#L807-L808

**Comment by abdelaziz-mahdy** [comment]
It's only a function call? I think I will have time next weekend if I start working on it will let you know

**Comment by rainyl** [comment]
Yes，just add the C wrappers in https://github.com/rainyl/dartcv/blob/1ba6e92ab11c563be9bee0607ceb182dcf18a6b6/dartcv/imgproc/imgproc.h#L807-L808 and corresponding dart codes in https://github.com/rainyl/opencv_dart/tree/main/packages/dartcv.

I am kind of busy recently, thank you in advance 😄

**Comment by abdelaziz-mahdy** [comment]
hi i created this pr https://github.com/rainyl/dartcv/pull/12, but when running make for ffigen it generates empty files 

when i looked at the configuration it tries to find the files in the src dir? which is empty since its in another repo, dont you think it should be in this repo to avoid this kind of problem?

i can make a pr for it if you dont mind, if there is a specific reason for it let me know 

since there is always the workaround of cloning the repo in the make file before generating (i just dont like it)

**Comment by abdelaziz-mahdy** [comment]
Will see how can I make it work, I have zero experience with cocopods 😅 so I may make a script to pull the src files to use in make file and delete them after it finishes.

For now it's a problem for tomorrow. Good night

**Comment by rainyl** [comment]
😄 Thanks, night~
